# Generated by Django 5.2.1 on 2025-06-26 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Audience Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Audience Description')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EventLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Label Name')),
                ('color', models.CharField(max_length=9, verbose_name='Label Color')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Sponsor Name')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='sponsors/', verbose_name='Sponsor Logo')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Sponsor Website')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Sponsor Description')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Event Name')),
                ('shortDescription', models.TextField(blank=True, null=True, verbose_name='Event Short Description')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Event Description')),
                ('startDate', models.DateField(blank=True, null=True, verbose_name='Event Start Date')),
                ('venue', models.CharField(blank=True, max_length=255, null=True, verbose_name='Venue')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Event Cover')),
                ('labels', models.ManyToManyField(related_name='events', to='events.eventlabel', verbose_name='Event Labels')),
                ('sponsors', models.ManyToManyField(related_name='events', to='events.sponsor', verbose_name='Sponsors')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
