# Generated by Django 5.2.1 on 2025-07-09 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='audiences',
            field=models.ManyToManyField(related_name='events', to='events.audience', verbose_name='Audiences'),
        ),
    ]
