# Generated by Django 5.2.1 on 2025-07-09 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_audiences'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='slug',
            field=models.SlugField(default='name', max_length=255, verbose_name='Event Slug'),
            preserve_default=False,
        ),
    ]
