[tool.poetry]
name = "Welead"
version = "0.1.0"
description = "Welead Web Application"
authors = ["Sasindu Wijethunga <e22445@eng.pdn.ac.lk>"]
license = "MIT"
readme = "README.md"
packages = [
    { include = "vvecon" },
]

[tool.poetry.dependencies]
python = "^3.10"
django = "^5.0.6"
djangorestframework = "^3.15.1"
django-split-settings = "^1.3.1"
pyyaml = "^6.0.1"
psycopg2-binary = "^2.9.9"
django-cors-headers = "^4.3.1"
django-filter = "^24.2"
djangorestframework-simplejwt = "^5.3.1"
daphne = "^4.1.2"
pytest = "^8.2.1"
pytest-xdist = "^3.6.1"
pytest-django = "^4.8.0"
model-bakery = "^1.18.0"
pymysql = "^1.1.1"
types-pymysql = "^1.1.0.20240524"
mypy = "^1.10.0"
requests = "^2.32.3"
asgiref = "^3.8.1"
pillow = "^10.3.0"
python-dotenv = "^1.0.1"
autobahn= "23.6.2"
icecream = "^2.1.3"
whitenoise = "^6.8.2"
django-ipware = "^7.0.1"
geoip2 = "^4.8.1"
django-allauth = "^65.4.0"
pyjwt = "^2.10.1"
django-jazzmin = "^3.0.1"

[tool.isort]
line_length = 119
multi_line_output = 5

[tool.yapf]
align_closing_bracket_with_visual_indent = true
based_on_style = "google"
coalesce_brackets = true
column_limit = 119
dedent_closing_brackets = true

[tool.poetry.group.dev.dependencies]
flake8 = "^7.0.0"
pre-commit = "^3.7.1"
colorlog = "^6.8.2"
django-livesync = "^0.5"
django-debug-toolbar = "^5.0.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

### Ruff Linter Settings ###
[tool.ruff]
line-length = 119
target-version = "py310"

[tool.ruff.lint]
select = ["E", "F", "W", "I", "B", "C", "Q", "N", "R"]
ignore = [
]
per-file-ignores = { "core/settings.py" = ["E501"] }
exclude = [
    "**/migrations/*",
    ".git",
    "__pycache__",
    ".venv"
]
max-complexity = 12

### Ruff Formatter Settings ###
[tool.ruff.format]
quote-style = "single"
indent-style = "tab"
line-ending = "lf"

### Ruff isort (Import Sorting) ###
[tool.ruff.lint.isort]
known-first-party = ["welead"]
lines-between-types = 1
lines-after-imports = 2
force-single-line = false
order-by-type = false