# Generated by Django 5.2.1 on 2025-05-18 10:26

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Banner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("image", models.ImageField(upload_to="banners/")),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("primaryButtonText", models.CharField(max_length=255)),
                ("primaryButtonLink", models.CharField(max_length=255)),
                ("secondaryButtonText", models.CharField(max_length=255)),
                ("secondaryButtonLink", models.CharField(max_length=255)),
                ("order", models.PositiveIntegerField(default=0)),
                ("isActive", models.BooleanField(default=True)),
                (
                    "page",
                    models.CharField(
                        choices=[("home", "Home")], default="home", max_length=20
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
