name: Quality Assurance
on:
  push:
    branches:
       - '**'
  pull_request:
    branches:
       - '**'

jobs:
  quality-assurance:
    name: Quality Assurance
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.8.3

      - name: Install dependencies
        run: make update

      - name: Lint
        run: make lint
